<html>
<head>
<title>Novitas Item Manager</title>
<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="/shared/jquery-ui/ui-lightness/jquery-ui-1.8.18.custom.css" type="text/css" />

<script type="text/javascript" src="/shared/jquery/jquery-1.7.1.min.js"> </script>
<script type="text/javascript" src="/shared/jquerytools/jquery.tools.min.js"></script>
<script type="text/javascript" src="/shared/jqueryforms/jquery.form.js"></script>
<script type="text/javascript" src="/shared/jquery-ui/jquery-ui.js"></script>
<script type="text/javascript" src="/shared/jquery.scrollTo/jquery.scrollTo-min.js"></script>

<script type="text/javascript" src="js/underscore-min.js"></script>
<script type="text/javascript" src="js/backbone-min.js"></script>
<script type="text/javascript" src="js/mustache.js"></script>

<script type="text/javascript" src="js/items.js"> </script>
<script type="text/javascript" src="js/mvc.js"> </script>
</head>
<body>
<div id="banner">
<h1>KON Item Database</h1>
</div>