<?php

$matches = array(
'axe' => array('Weapon', 'Axe'),
'sword' => array('Weapon', 'Sword'),
'katana' => array('Weapon', 'Sword'),
'gladius' => array('Weapon', 'Sword'),
'rapier' => array('Weapon', 'Sword'),
'saber' => array('Weapon', 'Sword'),
//'martial' => array('Martial', 'Weapon'),
'spear' => array('Great weapon', 'Weapon', 'Spear'),
'halbard' => array('Great weapon', 'Weapon', 'Spear'),
'dagger' => array('Weapon', 'Dagger'),
'bow' => array('Weapon', 'Ranged weapon'),
'thrown' => array('Weapon', 'Throwing weapon'),
'throwing' => array('Weapon', 'Throwing weapon'),
'arrow' => array('Ammunition'),
'bolt' => array('Ammunition'),
'mace' => array('Weapon', 'Mace'),

'magic' => 'Magic item',
'smite' => 'Additional smite',
'alchemy' => 'Production item',
'production' => 'Production item',

'feast' => 'Feb feast item',
'feast' => 'Feb feast item',

'silver' => 'Silver',
'elven steel' => 'Elven steel',
'elvensteel' => 'Elven steel',
'elven-steel' => 'Elven steel',
'goblin iron' => 'Goblin iron',
'goblin-iron' => 'Goblin iron',
'nature ' => 'Nature weapon',
'primal ' => 'Primal weapon',

'magic armor' => 'Magic armor',
'toughness' => 'Toughness',
'anti-magic shield' => 'Anti-magic shield',
'anti magic shield' => 'Anti-magic shield',
'antimagic shield' => 'Anti-magic shield',
'spirit shield' => 'Spirit shield',
'improved magic armor' => 'Improved magic armor',
'sanctuary' => 'Sanctuary',
'anti-magic aura' => 'Anti-magic aura',
'antimagic aura' => 'Anti-magic aura',
'anti magic aura' => 'Anti-magic aura',
'synchronize' => 'Synchronize',
'poison immunity' => 'Poison immunity',
'reflection' => 'Aura of reflection',

'magic strike' => 'Magic strike',
'strength' => 'Strength',
'magic swarm' => 'Magic swarm',
'mana burn' => 'Mana burn',
'slaying swarm' => 'Slaying swarm',
'spellstore' => 'Spellstore',
'spell store' => 'Spellstore',
'maelstrom' => 'Maelstrom',
'mealstrom' => 'Maelstrom',
'severance' => 'Severance',
'severence' => 'Severance',
'devastation' => 'Devastation',
'battle mastery' => 'Battle mastery',

'mend armor' => 'Mend armor',
'grounding' => 'Grounding',
'dissipate' => 'Dissipate',
'disipate' => 'Dissipate',
'dissapate' => 'Dissipate',
'repel nature' => 'Repel nature',
'natural repulsion' => 'Repel nature',
'elemental dart' => 'Elemental dart',
'elemental weapon' => 'Elemental weapon',
'banish' => 'Banish',
'nature\'s command' => 'Nature\'s command',
'command nature' => 'Nature\'s command',
'ley lines' => 'Ley lines',
'primal form' => 'Primal form',

'magic lock' => 'Magic lock',
'enhance armor' => 'Enhance armor',
'enchant shield' => 'Enchant shield',
'silvershine' => 'Silvershine',
'enchant weapon' => 'Enchant weapon',
'eldritch stone' => 'Eldritch stone',
'dispel magic' => 'Dispel magic',
'dispel' => 'Dispel magic',
'ablative armor' => 'Ablative armor',
'wraithbane' => 'Wraithbane',
'wraith bane' => 'Wraithbane',
'shadow skin' => 'Shadow skin',
'shadowskin' => 'Shadow skin',

'heal body' => 'Heal body',
'diagnosis' => 'Diagnosis',
'restore limb' => 'Restore limb',
'heal limb' => 'Restore limb',
'purify spirit' => 'Purify spirit',
'heal mortal wound' => 'Heal mortal wound',
'heal mortal' => 'Heal mortal wound',
'pacify' => 'Pacify',
'panacea' => 'Panacea',
'panacae' => 'Panacea',
'triage' => 'Triage',
'second breath' => 'Second breath',
'revive' => 'Revive',

'reap spirit' => 'Reap spirit',
'ghastly visage' => 'Ghastly visage',
'gastly visage' => 'Ghastly visage',
'repel undead' => 'Repel undead',
'creeping rot' => 'Creeping rot',
'sancitify' => 'Sanctify',
'curse' => 'Curse',
'lesser command' => 'Lesser command',
'unhallow' => 'Unhallow',
'abomination' => 'Abomination',
'greater command' => 'Greater command',

'weaken' => 'Weaken',
'disengage' => 'Disengage',
'charm' => 'Charm',
'silence' => 'Silence',
'pin' => 'pin',
'memory loss' => 'Memory loss',
'fear' => 'Fear',
'stun' => 'Stun',
'dominate' => 'Dominate',
'mind blank' => 'Mind blank',


' shield ' => 'Shield',
'buckler' => 'Buckler',

'tunic' => 'Torso slot',
'shirt' => 'Torso slot',
'vest' => 'Torso slot',
'tabard' => 'Torso slot',
'coat' => 'Torso slot',
'dress' => 'Torso slot',
'robe' => 'Torso slot',
'breastplate' => 'Torso slot',
'hauberk' => 'Torso slot',

'shoe' => 'Feet slot',
'sandal' => 'Feet slot',
'boot' => 'Feet slot',

'hat' => 'Head slot',
'helm' => 'Head slot',
'crown' => 'Head slot',
'coif' => 'Head slot',
'mask' => 'Head slot',

'greave' => 'Leg slot',
'pants' => 'Leg slot',
'skirt' => 'Leg slot',

'bracer' => 'Arm slot',

'belt' => 'Waist slot',
'sash' => 'Waist slot',

'spaulder' => 'Shoulder slot',
'mantle' => 'Shoulder slot',
'hood' => 'Shoulder slot',
'pauldron' => 'Shoulder slot',

'cloak' => 'Back slot',
'cape' => 'Back slot',

'glove' => 'Hand slot',
'gauntlet' => 'Hand slot',

'necklace' => 'Neck slot',
'choker' => 'Neck slot',
'gorget' => 'Neck slot',
'torc' => 'Neck slot',
'amulet' => 'Neck slot',
'pendant' => 'Neck slot',

'bracelet' => 'Wrist slot',
'manacle' => 'Wrist slot',
'ankle bracelet' => 'Ankle slot',
'ring' => 'Ring slot',

'tome' => 'Tome',
'ritual' => 'Ritual component',
'wand' => 'Wand',

'once' => '1xDay',
'twice' => '2xDay',
);

$id = $_REQUEST['id'];
$existing_tags = explode(',', $_REQUEST['tags']);

if ($id > 0) {

	$query = 'SELECT * FROM items WHERE item_id="' . $id . '" ';
	$GLOBALS['db']->query($query, SQL_INIT);
	$item = $GLOBALS['db']->record;

	$query = 'SELECT * FROM tags WHERE item_id="' . $id . '" ';
	$GLOBALS['db']->query($query, SQL_ALL);
	$rows = $GLOBALS['db']->record;

	foreach ($rows as $row) {
		if (!in_array($row['name'], $existing_tags)) $existing_tags[] = $row['name'];
	}
} else {
	$item = array();
	$item['description'] = $_REQUEST['description'];
	$item['notes'] = $_REQUEST['notes'];
	$item['value'] = $_REQUEST['value'];
	
	$tags = $_REQUEST['tags'];
	if ($tags) $existing_tags = explode(', ', $tags);
}

//print_r($existing_tags);

$new_tags = array();
foreach ($matches as $match=>$suggest) {
	$add = array();
	if (stristr($item['description'], $match) || stristr($item['notes'], $match)) {
		if (is_array($suggest)) {
			$add = $suggest;
		} else {
			$add[] = $suggest;
		}
	}
	if (count($add) > 0) {
		foreach ($add as $t) {
			if (!in_array($t, $existing_tags)) $new_tags[] = $t;
		}
	}

	if ($item['value'] > 0) $new_tags[] = 'Treasure';
}
//sort($new_tags);
echo implode(', ', array_unique($new_tags));

?>